name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:

      # download our git repository to our current environment
      # view: https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          target: builder_cache
          outputs: type=docker,dest=/tmp/base_image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            base-builder:latest
  
  build-code:
    runs-on: ubuntu-latest
    needs: build-base
    steps:

      #for having access to our source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with src
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          target: src_builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker
          tags: |
            src-builder:latest
      
      - name: test show images
        run: docker images
      
      - name: test list containers
        run: docker container ls

      - name: test run
        run: docker run --name teste src-builder
      
      - name: test list containers
        run: docker container ls