name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@vmaster
        with:
          install: true
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: base_image:latest
          push: false
          target: builder_cache
          outputs: type=docker,dest=/tmp/base_image.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base_image
          path: /tmp/base_image.tar
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-code:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: base_image
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base_image.tar
          docker image ls -a
      
      -
        name: Build for run
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /Dockerfile
          tags: final_image:latest
          target: builder
          push: false
