name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: base_image:latest
          target: builder_cache
          outputs: type=docker,dest=/tmp/base_image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base_image
          path: /tmp/base_image.tar

  build-code:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: base_image
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base_image.tar
          docker image ls -a
      
      -
        name: Build for run
        run: DOCKER_BUILDKIT=1 docker build --build-arg BUILDER_IMAGE=base_image:latest .